# Generated by Django 6.0.3 on 2026-03-14 10:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Purchase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_email', models.EmailField(db_index=True, max_length=254)),
                ('total_without_tax', models.FloatField(default=0.0)),
                ('total_tax', models.FloatField(default=0.0)),
                ('net_total', models.FloatField(default=0.0)),
                ('rounded_total', models.FloatField(default=0.0)),
                ('cash_paid', models.FloatField(default=0.0)),
                ('balance_returned', models.FloatField(default=0.0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'purchases',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PurchaseItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField()),
                ('unit_price', models.FloatField()),
                ('tax_percentage', models.FloatField()),
                ('purchase_price', models.FloatField()),
                ('tax_amount', models.FloatField()),
                ('total_price', models.FloatField()),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='purchase_items', to='products.product')),
                ('purchase', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='billing.purchase')),
            ],
            options={
                'db_table': 'purchase_items',
            },
        ),
    ]
