# Generated by Django 6.0.3 on 2026-03-14 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('price', models.FloatField(help_text='Price per unit')),
                ('stock', models.PositiveIntegerField(help_text='Available stock quantity')),
                ('tax_percentage', models.FloatField(help_text='Tax percentage e.g. 18 for 18%')),
            ],
            options={
                'db_table': 'products',
                'ordering': ['name'],
            },
        ),
    ]
